### ISSUE TITLE
Delphi 10.3

### ISSUE THREAD

**Issue by MarcosFincotto** [marcobreveglieri/horse-prometheus-metrics#2]
Projeto maravilhoso, mas acredito que tenha sido feito com 10.4, gerando assim incompatibilidade com algumas classes.

**Comment by marcobreveglieri** [comment]
> Projeto maravilhoso, mas acredito que tenha sido feito com 10.4, gerando assim incompatibilidade com algumas classes.

Hi Marcos,

I have used Delphi 11 and some of the latest features added to the Delphi language, eg. inline variable declaration, so **the code may not be compatible with older versions of Delphi**.

Prometheus Client is a rather **new** project, aimed to help those who are building modern (micro)services that needs to be monitored, using a recent version of Delphi (or migrating legacy code to one of the latest releases).

At the beginning of the project, I thought about compatibility issues but I've managed to prefer keeping the code simple, readable and more modern rather than guaranteeing its functioning with past and outdated Delphi versions, sorry. :|

That said, if more developers would ask for support of old Delphi versions, I might reconsider it in the future.

Thanks for your feedback! ❤️
Marco.

**Comment by MarcosFincotto** [comment]
Hello Marco, I appreciate your feedback. I'm talking about versions like 10.3 (Rio), for example. I'm going to fork the project and adjust it to my needs, as it is, I'll do a pull and you'll analyze the feasibility of including them in the official source.

**Comment by marcobreveglieri** [comment]
> Hello Marco, I appreciate your feedback. I'm talking about versions like 10.3 (Rio), for example. I'm going to fork the project and adjust it to my needs, as it is, I'll do a pull and you'll analyze the feasibility of including them in the official source.

Hi Marcos,
my intention was to avoid forcing you or other developers to make efforts in doing any changes, but if you have the time and the desire of working on this, I will definitely look forward to them and considering merge the changes! 🤗

Write me if you have any doubts or requests.

Thanks! ❤️
Marco.

**Comment by marcobreveglieri** [comment]
Hi @MarcosFincotto,
I don't know if you had the chance to solve your problem. In any case, since it is a borderline problem, I close the issue renewing my availability to evaluate changes to make the project compatible with other previous versions of Delphi, where possible (keeping the modern ispiration of the project).

Thanks again!
Marco.
